In [2]:
import pandas as pd

btc = pd.read_csv('data/model/btc_model_price.csv')
btc

,Unnamed: 0,Date,Price,Open,High,Low,Volume,pct_change,TVL,weighted_sentiment,...,MA_td,3MA_td,%K_td,%D_td,RSI_td,Momentum_td,MACD_td,CCI_td,Wikipedia_Views_x,Google_Trends_x
0,0,2024-06-11,67191.4,69537.9,69573.3,66766.3,81720.0,-0.0337,1.104884e+09,-0.055700,...,0,0,0,0,0,0,0,0,4501,25.0
1,1,2024-06-10,69538.2,69650.2,70152.5,69259.9,39120.0,-0.0016,1.164491e+09,0.373901,...,0,0,0,0,0,0,1,0,4316,20.0
2,2,2024-06-09,69650.6,69310.5,69847.8,69136.7,20990.0,0.0049,1.158554e+09,0.119032,...,0,0,0,0,0,0,1,0,4082,19.0
3,3,2024-06-08,69310.1,69347.0,69572.1,69222.4,23030.0,-0.0005,1.159399e+09,-0.052684,...,0,0,0,0,0,0,1,0,4084,23.0
4,4,2024-06-07,69347.9,70793.4,71956.5,68620.7,82620.0,-0.0204,1.186341e+09,-0.070606,...,0,0,0,0,0,0,1,0,4392,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,158,2024-01-05,44156.9,44163.0,44312.1,42629.0,68070.0,0.0000,3.191424e+08,NaN,...,0,1,1,0,0,1,0,0,7212,41.0
159,159,2024-01-04,44157.0,42836.1,44744.5,42632.8,68050.0,0.0308,3.095193e+08,NaN,...,0,1,0,1,0,1,0,0,9113,38.0
160,160,2024-01-03,42836.1,44943.7,45492.7,40888.3,117650.0,-0.0469,3.256931e+08,NaN,...,0,1,0,0,0,0,0,0,15761,49.0
161,161,2024-01-02,44943.7,44182.9,45885.4,44166.0,97840.0,0.0172,3.163287e+08,NaN,...,0,1,1,1,0,1,1,0,9267,49.0
162,162,2024-01-01,44183.4,42272.5,44187.0,42196.7,36300.0,0.0452,3.058496e+08,NaN,...,0,1,0,1,0,0,1,0,6371,30.0