In [10]:
# Basic Stack 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import sys
import os
import importlib

# Changing the working directory
path = ('P:/6. DSMA/99. Thesis/Github/thesis')
os.chdir(path)

# Import the module
sys.path.append('P:/6. DSMA/99. Thesis/Github/thesis/scripts')
import pipeline_crypto_prices
from pipeline_crypto_prices import get_prices
import camel
import sentiment_analyzer
importlib.reload(pipeline_crypto_prices)
importlib.reload(camel)
importlib.reload(sentiment_analyzer)

In [11]:
btc

NameError: name 'btc' is not defined

In [7]:
all_ext

,Date,Bitcoin,Solana,Ethereum,Cryptocurrency,Crypto,Blockchain,BTC_Gtrends,ETH_Gtrends,SOL_Gtrends,Crypto_Gtrends
0,2024-01-01,6371.0,31.0,986.0,2903.0,21.0,1610.0,32,25,38,44
1,2024-01-02,9267.0,39.0,1403.0,3776.0,22.0,1920.0,49,32,49,52
2,2024-01-03,15761.0,24.0,1546.0,6240.0,27.0,8255.0,53,29,42,59
3,2024-01-04,9113.0,24.0,1382.0,4493.0,29.0,2444.0,45,26,41,50
4,2024-01-05,7212.0,32.0,1317.0,4049.0,23.0,2072.0,43,24,36,48
...,...,...,...,...,...,...,...,...,...,...,...
185,2024-07-04,4231.0,17.0,1076.0,2895.0,27.0,1673.0,35,23,29,42
186,2024-07-05,4547.0,12.0,1039.0,3093.0,28.0,1848.0,42,26,30,48
187,2024-07-06,4101.0,13.0,1007.0,2290.0,25.0,1326.0,30,20,29,40
188,2024-07-07,4243.0,23.0,1036.0,2326.0,26.0,1452.0,28,19,26,38
189,2024-07-08,NaN,NaN,NaN,NaN,NaN,NaN,34,23,26,41